### ISSUE TITLE
Math image in README is hard to read in dark mode

### ISSUE THREAD

**Issue by DanielVandH** [Datseris/ARFIMA.jl#8]
Here's what it looks like:

![ccb241f3225f1ebd04f5c283ff8163c6](https://github.com/JuliaDynamics/ARFIMA.jl/assets/95613936/926634d3-ef43-41dc-8c63-e8da256b311f)

Is it possible to somehow render this to be dark mode friendly, e.g. with LaTeX directly? I tried something like

```math
\underbrace{\left(1 - \sum_{i=1}^p \varphi_i B^i\right)}_{\text{\textcolor{blue}{auto-regressive}}}\underbrace{\left(1 - B\right)^{\overbrace{d}^{\text{\textcolor{purple}{fractional if $d \in \mathbb R$}}}}}_{\text{\textcolor{orange}{integrated}}} \underbrace{X_t}_{\text{\textcolor{gray}{generated timeseries}}} = \underbrace{\left(1 - \sum_{i=1}^q \theta_i\theta^i\right)}_{\text{\textcolor{green}{moving average}}}\underbrace{\varepsilon_t}_{\text{\textcolor{red}{white noise}}},
```

but that's worse, obviously (since GitHub can't get the actual packages needed to create the same type of image).

**Comment by Datseris** [comment]
Oh, alas, I no longer have the original file...

There is a very simple way to fix it. Download the image, and put behind it a white background. The problem now is that hte image is transparent.
